### ISSUE TITLE
XML Parse error

### ISSUE THREAD

**Issue by dac09** [miguelpuyol/Jira-Alfred-Workflow#1]
Hi Miguel,

I'm using a slightly changed version of your script to search Jira - was working perfectly for the past few months, but it seems to have broken recently throwing:

```
[ERROR: alfred.workflow.input.scriptfilter] XML Parse Error 'The operation couldn’t be completed. (NSXMLParserErrorDomain error 33.)'. Row (null), Col (null): 'String not started expecting ' or "' in XML:
```

Any ideas on how to fix this?

Thanks,
Daniel

Btw - I've added a very simple implementation of caching, I'll create a PR when I've fixed this issue with your help

**Comment by dac09** [comment]
Really sorry I seem to have posted to the wrong repository.

**Comment by miguelpuyol** [comment]
Hey do not worry about it. Could you let me know what other JIRA project are you referring to? I am interesting in seing what others are doing!

**Comment by dac09** [comment]
Hey,

Here's my forked version: https://github.com/dac09/search-jira-issues-alfred-workflow and the original: https://github.com/swissmanu/search-jira-issues-alfred-workflow

I'm not too familiar with jsawk and general bash scripting for generally complicated stuff like this - but this seems to work really well for me.

Thanks,
Danny

**Comment by miguelpuyol** [comment]
Thanks! That is a really interesting project!

This one uses python-jira and the workflow library for python. I am not so brave to handle it all by "hand".
