### ISSUE TITLE
where can I find 'Apple Keychain service' and ' Greenhopper Board Id'?

### ISSUE THREAD

**Issue by mekhovov** [miguelpuyol/Jira-Alfred-Workflow#2]
hey, @miguelpuyol  I really like your plugin functionality :+1: and want to try it :)

can you help me configure this workflow please?

how can I get values for these options?
- setupjirakeychain   Set the Apple Keychain service where your JIRA password is stored
- setupjirasprintboard    Set the Greenhopper Board Id

have no idea what is and where to find these values :(

**Comment by miguelpuyol** [comment]
Hi there!

First of all, thanks for testing it! 

Regaring your questions, assuming you know what the Keychain is, it is the name of the account where you stored your Jira password. In the image below, I called it jira@alfred, and I stored my email and password
<img width="745" alt="screencapture at wed sep 23 09 41 25 cest 2015" src="https://cloud.githubusercontent.com/assets/3450789/10040022/43d1e0c0-61d8-11e5-81dc-4c641c830521.png">

For the Greenhopper Board Id, this plugins is so far only available for JIRA agile boards. For example, if you access your Scrum Board in `https://jira.myorg.com/secure/RapidBoard.jspa?rapidView=432`, the id you have to provide to `setupjirasprintboard` is 432

As a workaround, you can check a specific story with the --story modifier:
`jira --story BUG-607` where BUG-607 is an story key in Jira.

I hope this helps!

**Comment by jonnnylingo** [comment]
FWIW, I had to put the value for **Where** rather than **Name** of the key.  In the example above they are both the same but I assumed it was **Name**.  I have a different value for **Where**.  Once I passed that value to setupjiraserver it found the password just fine.

**Comment by miguelpuyol** [comment]
Thanks for checking it out. I am planning to add also a simpler way of storing your password directly in the Keychain from the workflow.

Follow #4 and #5

**Comment by miguelpuyol** [comment]
Hey I just created a new version 0.3.5 where you can now set the password directly from the Workflow.

You could install the new workflow from here or by running `jira workflow:update` in alfred!

I will try to add also the sprint board selection later today

**Comment by mekhovov** [comment]
@miguelpuyol many thanks for your help! it works for me! :+1: 
have another problem :( added issue https://github.com/miguelpuyol/Jira-Alfred-Workflow/issues/6
