### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jonnnylingo** [miguelpuyol/Jira-Alfred-Workflow#3]
I get an IndexError when trying to run **jira** from alfred.  It appears it is connecting correctly to the jira server but when it processes the list of sprints from jira it throws this error.

Here are some screen shots:

This is the error log in the aleph console.
![error log](https://cloud.githubusercontent.com/assets/869403/10086716/2f4042e6-62cd-11e5-8591-a933981ebe32.jpg)

This is what I see when typing "jira" into aleph.
![jira](https://cloud.githubusercontent.com/assets/869403/10086726/386641cc-62cd-11e5-9c73-f3c240334230.jpg)

Here is my Jira Setup.
![setup2](https://cloud.githubusercontent.com/assets/869403/10086807/a9d30282-62cd-11e5-9589-ca3028102456.jpg)

**Comment by miguelpuyol** [comment]
Hi jonnnylingo,

It seems to me that you have no sprint created for your board. 

I will try to provide a fix to avoid the error and show a more meaningul message.

**Comment by jonnnylingo** [comment]
I do have a sprint created.  I am in the middle of a 2 week sprint right now.  Is there anything else I can provide to help troubleshoot?

**Comment by miguelpuyol** [comment]
This ugly error should be fixed in v0.3.5.
